#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed hyprland hyprlock hyprpaper
sudo pacman -S --noconfirm --needed waybar ttf-jetbrains-mono-nerd
sudo pacman -S --noconfirm --needed alacritty thunar wofi
yay -S --noconfirm --needed brave-bin
